Training Epoch 1/30:   0%|                                            | 0/3100 [00:01<?, ?it/s]
torch.Size([1])
cuda:0
cuda:0
Traceback (most recent call last):
  File "/cluster/home/debaumann/cars_paper/attention_vit.py", line 260, in <module>
    main()
  File "/cluster/home/debaumann/cars_paper/attention_vit.py", line 111, in main
    hand_loss = F.mse_loss(hand, hand_heatmap)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/debaumann/miniconda3/envs/transformer/lib/python3.11/site-packages/torch/nn/functional.py", line 3792, in mse_loss
    return torch._C._nn.mse_loss(
           ^^^^^^^^^^^^^^^^^^^^^^
RuntimeError: CUDA error: device-side assert triggered
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
