Training Epoch 1/30: 100%|█████████████████████████████████| 3100/3100 [21:32<00:00,  2.40it/s]
Epoch [1/30] Train: Loss: 105797.6963, Class Loss: 3.9687, Hand Loss: 1738.2664, Obj Loss: 3551.4200, Accuracy: 0.0416
Validation Epoch 1/30:   0%|                                           | 0/962 [00:00<?, ?it/s]Clipping input data to the valid range for imshow with RGB data ([0..1] for floats or [0..255] for integers). Got range [-0.7882353..1.0].
Validation Epoch 1/30:   0%|                                           | 0/962 [00:01<?, ?it/s]
Traceback (most recent call last):
  File "/cluster/home/debaumann/cars_paper/attention_vit.py", line 260, in <module>
    main()
  File "/cluster/home/debaumann/cars_paper/attention_vit.py", line 217, in main
    axes[3, j].imshow(hand_att_np, cmap='hot')
  File "/cluster/home/debaumann/miniconda3/envs/transformer/lib/python3.11/site-packages/matplotlib/__init__.py", line 1473, in inner
    return func(
           ^^^^^
  File "/cluster/home/debaumann/miniconda3/envs/transformer/lib/python3.11/site-packages/matplotlib/axes/_axes.py", line 5895, in imshow
    im.set_data(X)
  File "/cluster/home/debaumann/miniconda3/envs/transformer/lib/python3.11/site-packages/matplotlib/image.py", line 729, in set_data
    self._A = self._normalize_image_array(A)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/cluster/home/debaumann/miniconda3/envs/transformer/lib/python3.11/site-packages/matplotlib/image.py", line 697, in _normalize_image_array
    raise TypeError(f"Invalid shape {A.shape} for image data")
TypeError: Invalid shape (8, 496, 496) for image data
